name: CI

on:
  push:
  pull_request:

jobs:
  sozo-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: curl -L https://install.dojoengine.org | bash
    - run: /home/runner/.config/.dojo/bin/dojoup -v v0.3.4
    - run: |
        cd contracts
        /home/runner/.config/.dojo/bin/sozo build
    - run: |
        cd contracts
        /home/runner/.config/.dojo/bin/sozo test
